export const LOCATIONS_CORD_SET = 'LOCATIONS_CORD_SET'
export const LOCATIONS_ALL_SET = 'LOCATIONS_ALL_SET'
export const LOCATIONS_ONE_SET = 'LOCATIONS_ONE_SET'
export const LOCATIONS_REMOVE_ONE = 'LOCATIONS_REMOVE_ONE'
